# Autogenerated wrapper script for helpme_jll for x86_64-linux-gnu-cxx03
export libhelpme

using FFTW_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("helpme")
JLLWrappers.@declare_library_product(libhelpme, "libhelpme.so")
function __init__()
    JLLWrappers.@generate_init_header(FFTW_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libhelpme,
        "lib/libhelpme.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
